FROM arm64v8/golang:1.12-rc-alpine3.8 AS build-env

COPY /tiny_go_web_server.go .

RUN go build -o tiny_go_web_server tiny_go_web_server.go && ls && pwd


FROM alpine

WORKDIR /

COPY --from=build-env /go/tiny_go_web_server .

COPY /tiny_go_web ./tiny_go_web

EXPOSE 8282

CMD  ["./tiny_go_web_server"]
